const sampleJobs = [
  {
    title: "Backend Developer",
    description: "Develop robust APIs with Node.js and Express for scalable applications.",
    company: "TechNova Solutions",
    location: "Bangalore",
    salary: "₹8,00,000",
    type: "Full-time",
    skillsRequired: ["Node.js", "Express", "MongoDB", "REST APIs"],
    experience: "1-3 years",
    contactEmail: "hr@technova.in",
    postedAt: new Date("2025-07-01"),
    applyBy: new Date("2025-07-31"),
  },
  {
    title: "Frontend Intern",
    description: "Assist UI development using React, Tailwind CSS, and animations.",
    company: "PixelPlay Studios",
    location: "Remote",
    salary: "₹15,000",
    type: "Internship",
    skillsRequired: ["React", "JavaScript", "CSS"],
    experience: "0-1 years",
    contactEmail: "interns@pixelplay.com",
    postedAt: new Date("2025-07-02"),
    applyBy: new Date("2025-07-20"),
  },
  {
    title: "DevOps Engineer",
    description: "Setup CI/CD pipelines and automate cloud deployments using Kubernetes.",
    company: "CloudForge Labs",
    location: "Hyderabad",
    salary: "₹12,00,000",
    type: "Full-time",
    skillsRequired: ["Docker", "Kubernetes", "AWS", "Jenkins"],
    experience: "2+ years",
    contactEmail: "careers@cloudforge.io",
    postedAt: new Date("2025-07-03"),
    applyBy: new Date("2025-08-05"),
  },
  {
    title: "Python Developer",
    description: "Create predictive models using Python and Scikit-learn for real-world datasets.",
    company: "InsightML",
    location: "Mumbai",
    salary: "₹9,50,000",
    type: "Full-time",
    skillsRequired: ["Python", "Pandas", "Scikit-learn"],
    experience: "1-2 years",
    contactEmail: "jobs@insightml.in",
    postedAt: new Date("2025-07-04"),
    applyBy: new Date("2025-08-01"),
  },
  {
    title: "Content Strategist",
    description: "Design engaging content for LinkedIn and YouTube Shorts with a growth mindset.",
    company: "GrowthFlare Media",
    location: "Remote",
    salary: "₹4,00,000",
    type: "Part-time",
    skillsRequired: ["Copywriting", "SEO", "Social Media"],
    experience: "1+ years",
    contactEmail: "hello@growthflare.io",
    postedAt: new Date("2025-07-05"),
    applyBy: new Date("2025-07-25"),
  },
  {
    title: "Data Analyst",
    description: "Analyze customer behavior and provide actionable insights via visualization.",
    company: "DataLoop Insights",
    location: "Pune",
    salary: "₹6,80,000",
    type: "Full-time",
    skillsRequired: ["Excel", "SQL", "Tableau", "Python"],
    experience: "1-3 years",
    contactEmail: "recruit@dataloop.com",
    postedAt: new Date("2025-07-06"),
    applyBy: new Date("2025-08-02"),
  },
  {
    title: "UI/UX Designer",
    description: "Design user-first interfaces and prototypes using Figma.",
    company: "SnapDesigns",
    location: "Indore",
    salary: "₹5,50,000",
    type: "Full-time",
    skillsRequired: ["Figma", "Adobe XD", "User Research"],
    experience: "1-2 years",
    contactEmail: "designs@snapstudio.in",
    postedAt: new Date("2025-07-07"),
    applyBy: new Date("2025-08-10"),
  },
  {
    title: "Machine Learning Intern",
    description: "Train linear regression models and explore data science workflows.",
    company: "CoreAI Labs",
    location: "Remote",
    salary: "₹10,000",
    type: "Internship",
    skillsRequired: ["Python", "NumPy", "Matplotlib", "Linear Regression"],
    experience: "0-1 years",
    contactEmail: "interns@coreailabs.com",
    postedAt: new Date("2025-07-08"),
    applyBy: new Date("2025-07-30"),
  },
  {
    title: "System Admin",
    description: "Monitor servers and perform system upgrades across cloud-hosted platforms.",
    company: "SysSphere",
    location: "Chennai",
    salary: "₹7,20,000",
    type: "Full-time",
    skillsRequired: ["Linux", "Networking", "AWS", "Security"],
    experience: "2+ years",
    contactEmail: "support@syssphere.in",
    postedAt: new Date("2025-07-09"),
    applyBy: new Date("2025-08-03"),
  },
  {
    title: "Digital Marketer",
    description: "Drive campaign success using paid ads, email funnels, and analytics.",
    company: "BoostEdge",
    location: "Ahmedabad",
    salary: "₹4,80,000",
    type: "Part-time",
    skillsRequired: ["Google Ads", "Meta Ads", "Email Marketing"],
    experience: "1+ years",
    contactEmail: "boost@boostedge.io",
    postedAt: new Date("2025-07-10"),
    applyBy: new Date("2025-07-28"),
  },
];

module.exports = { data: sampleJobs };